apiVersion: apps/v1
kind: Deployment
metadata:
  name: omke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omke
  template:
    metadata:
      labels:
        app: omke
    spec:
      containers:
      - image: okteto.dev/omke:latest
        name: omke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "66eb41d1-bfe9-4121-b40d-d48caa11b5c8"
        - name: Vless_Path
          value: "/66eb41d1-bfe9-4121-b40d-d48caa11b5c8"
        - name: Vmess_UUID
          value: "3c14a51d-cbb0-4e19-ac83-387d1e412e8f"
        - name: Vmess_Path
          value: "/3c14a51d-cbb0-4e19-ac83-387d1e412e8f"
        - name: Share_Path
          value: "/v2link"
